### ISSUE TITLE
Suggestion to remove all overrides

### ISSUE THREAD

**Issue by NamelessCoder** [sitegeist/fluid-components#3]
This is a suggestion to refactor the logic in this extension so it does not need to override the classes it currently does. It is in my opinion not a safe integration, primarily due to the fact that you short-circuit both the ViewHelper resolving logic and the template compiling. Neither are really safe to override in this way and it definitely causes incompatibility with any other project that might replace either of those. It is a little bit shocking for me as Fluid developer to see overrides of `NodeConverter` and `ViewHelperResolver` in projects because anything they do should be equally possible to achieve with the *right* API in Fluid.

Recommendations:

1. `<fc:component>` is redundant and appears to serve the same purpose as a section except without a name. I'd advise to refactor so the definitions of elements occurs in sections and you call `$view->renderSection()` when you need to extract metadata. That also allows you to use sections to put multiple components in the same file.
2. Do not make your argument VH `ParserRuntimeOnly` - instead, maintain an instance of whichever DSO you need to use, in `ViewHelperVariableContainer`. This can be extracted after rendering a section, which is how you can extract the metadata without overriding the ViewHelperResolver and NodeConverter.
3. Consider creating your components as `RenderableInterface` components instead. This can be rendered with `f:render` and can accept arguments like `f:render` (by taking the `arguments` that normally become variables and using them as input arguments).

If you combine these recommendations you would end up with a significantly safer and cleaner implementation. Take for example a hint from how Flux works to extract metadata from templates: https://github.com/FluidTYPO3/flux.

**Comment by s2b** [comment]
Thank you for your helpful feedback! To be honest, I found it quite hard to understand the inner workings of Fluid, which is probably why my implementation isn't ideal. I looked at the [documentation](https://github.com/TYPO3/Fluid/blob/master/doc/FLUID_IMPLEMENTATION.md) and chose the extension point that looked promising (`ViewHelperResolver`). I'm less confident about my decision to overwrite `NodeConverter` (and, to do that, `RenderingContext`), which became necessary when the default values needed to be dynamic. I will certainly look into the suggestions you provided as well as the flux implementation.

However, some of the points you mentioned are like this because they are important for the idea I wanted to implement with this extension:

* A component should be called "component" (not "section"), because that is what frontend developers already work with client-side. Also, they work differently, as you can only access sections in your current context (as defined by template/partial/layoutRootPaths), whereas my components can be required from elsewhere just like ViewHelpers.
* In my opinion, one file should only define one component. If you place the matching CSS and (possibly) JS file inside the same folder as the component definition, you can easily transfer one component from one project to another. In addition it forces users to focus on one isolated markup snippet without all of its dependencies.

Thanks again for your feedback. I'll leave this issue open and look into it when I find the time. :-)

**Comment by s2b** [comment]
With v2.0 I was able to remove the overrides for `NodeConverter` as well as `RenderingContext`. The one still remaining is `ViewHelperResolver`, which is fine for me.

I'm eager to test fluid3 once it's ready and will probably provide a converter from our components to fluid3 components.
